spring:
   profiles: 
       active:
       - dev
---
server:
   port: 7001

spring:
   profiles: dev
   application:
       name: microservicecloud-config-eureka-client

eureka: 
  instance:
    hostname: ec2-13-250-34-5.ap-southeast-1.compute.amazonaws.com #eureka server instance
  client: 
    register-with-eureka: false     
    fetch-registry: false     
    service-url: 
      defaultZone: http://ec2-13-250-34-5.ap-southeast-1.compute.amazonaws.com:37002/eureka/
---
server:
   port: 7001

spring:
   profiles: test
   application:
       name: microservicecloud-config-eureka-client

eureka: 
  instance:
    hostname: ec2-13-250-34-5.ap-southeast-1.compute.amazonaws.com #eureka server instance
  client: 
    register-with-eureka: false     
    fetch-registry: false     
    service-url: 
      defaultZone: http://ec2-13-250-34-5.ap-southeast-1.compute.amazonaws.com:37002/eureka/
