spring:
   profiles: 
       active:
       - dev
---
server:
  port: 8001

spring:
   profiles: dev
   application: 
    name: microservicecloud-config-provider-client
   
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://ec2-52-221-197-195.ap-southeast-1.compute.amazonaws.com:37001/eureka/ 
  
  instance:
    instance-id: microservice-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
  app.name: microservicecloud
  company.name: www.amazon.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
